# Site settings
title: Stanford LangCog Lab
email: bsparks@stanford.edu
description: >
  Stanford Language and Cognition Lab
  (affectionately called LangCog Lab)
url: https://langcog.github.io
repository: langcog/langcog.github.io
github_username:  bsparks98

gems: ['jekyll/scholar']

# Build settings
markdown: kramdown

max_year: 2022 #the most recent year with papers published
# i should figure out how to automate that...

exclude:
  - "files"
  - "wikiuploads"
  - "ignore"

exclude: [vendor]

keep_files:
  - "files"
  - "wikiuploads"

# for BibTeX
scholar:
  style: apa
  locale: en

  sort_by: year
  order: descending

  bibliography_list_tag: ul

  source: ./_bibliography
  bibliography: citations
  bibliography_template: <p>{{reference}} {{entry.annote}}</p>

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   "[Abstract/BibTeX]"

  query: "@*"

